Add  这个.物体识别数据集难倒了世界上最好的计算机视觉模型.md
opensourceai/spark-plan pull request #49
Opened 2019-12-11 08:01 UTC by heqiang

2019-12-11 08:03 UTC, chenquan commented on article/2019/12/这个物体识别数据集难倒了世界上最好的计算机视觉模型.md
> +##### 这个物体识别数据集难倒了世界上最好的计算机视觉模型
有图片吗？你放几张图片吧

2019-12-11 08:04 UTC, chenquan commented on article/2019/12/这个物体识别数据集难倒了世界上最好的计算机视觉模型.md
> +作者： Kim Martineau
```suggestion
作者：Kim Martineau 
```

2019-12-11 08:04 UTC, chenquan commented on article/2019/12/这个物体识别数据集难倒了世界上最好的计算机视觉模型.md
> +地址： https://news.mit.edu/2019/object-recognition-dataset-stumped-worlds-best-computer-vision-models-1210
```suggestion
地址：https://news.mit.edu/2019/object-recognition-dataset-stumped-worlds-best-computer-vision-models-1210 
```

2019-12-11 08:05 UTC, heqiang commented on article/2019/12/这个物体识别数据集难倒了世界上最好的计算机视觉模型.md
> +##### 这个物体识别数据集难倒了世界上最好的计算机视觉模型
我加一张吧

2019-12-11 13:49 UTC, chenquan commented on article/2019/12/这个物体识别数据集难倒了世界上最好的计算机视觉模型.md
> +##### 这个物体识别数据集难倒了世界上最好的计算机视觉模型
> 我加一张吧

图片,图片,记得加上

2019-12-11 13:54 UTC, heqiang commented on article/2019/12/这个物体识别数据集难倒了世界上最好的计算机视觉模型.md
> +##### 这个物体识别数据集难倒了世界上最好的计算机视觉模型
ok

2019-12-11 14:10 UTC, chenquan requested changes

2019-12-11 14:10 UTC, chenquan commented on article/2019/11/python高级用法之  三大高阶内置函数介绍
> +![image-20191117193727436](C:\Users\Hq\AppData\Roaming\Typora\typora-user-images\image-20191117193727436.png)
这里图片也没有

2019-12-11 14:10 UTC, chenquan commented on article/2019/11/python高级用法之  三大高阶内置函数介绍
> +![image-20191117193807736](C:\Users\Hq\AppData\Roaming\Typora\typora-user-images\image-20191117193807736.png)
图片

2019-12-11 14:10 UTC, chenquan commented on article/2019/11/python高级用法之  三大高阶内置函数介绍
> +![image-20191117193552078](C:\Users\Hq\AppData\Roaming\Typora\typora-user-images\image-20191117193552078.png)代码示例
图片

2019-12-12 02:37 UTC, heqiang commented on article/2019/11/python高级用法之  三大高阶内置函数介绍
> +![image-20191117193727436](C:\Users\Hq\AppData\Roaming\Typora\typora-user-images\image-20191117193727436.png)
那个新的翻译图片添加了 这个的我改下

2019-12-12 02:50 UTC, chenquan commented
@heqiang 文件名 有一个没有加`md`

2019-12-12 02:53 UTC, heqiang commented
> 
> 
> @heqiang 文件名 有一个没有加`md`

有个重复了 我删掉了 现在是对的了

2019-12-12 02:54 UTC, heqiang commented on article/2019/11/python高级用法之  三大高阶内置函数介绍
> +![image-20191117193807736](C:\Users\Hq\AppData\Roaming\Typora\typora-user-images\image-20191117193807736.png)
可以合并了

2019-12-12 02:54 UTC, chenquan commented
> > @heqiang 文件名 有一个没有加`md`
> 
> 有个重复了 我删掉了 现在是对的了

把文件名的空格去掉

2019-12-12 02:56 UTC, heqiang commented
> > > @heqiang 文件名 有一个没有加`md`
> > 
> > 
> > 有个重复了 我删掉了 现在是对的了
> 
> 把文件名的空格去掉
好了

2019-12-12 03:03 UTC, chenquan commented
![image](https://user-images.githubusercontent.com/20548053/70679061-05d6e980-1ccf-11ea-8b6b-c067750dc681.png)
@heqiang

2019-12-12 03:27 UTC, heqiang commented
> ![image](https://user-images.githubusercontent.com/20548053/70679061-05d6e980-1ccf-11ea-8b6b-c067750dc681.png)
> @heqiang

好了

2019-12-12 04:21 UTC, merged