Add 2019年对话式AI的10篇重要研究论文.md
opensourceai/spark-plan pull request #57
Opened 2019-12-13 07:51 UTC by heqiang

2019-12-13 07:53 UTC, chenquan commented
老哥，是我的库。你这个还是主库啊

2019-12-13 07:55 UTC, heqiang commented
> 老哥，是我的库。你这个还是主库啊

what？

2019-12-15 02:44 UTC, chenquan commented
![image](https://user-images.githubusercontent.com/20548053/70857368-d40c8f80-1f27-11ea-8ca8-3c7ed1806854.png)
trolls 
@heqiang

2019-12-15 04:19 UTC, chenquan commented on article/2019/12/2019年对话式AI的10篇重要研究论文.md
> + 对域本体的过度依赖和跨域知识共享的缺乏是对话状态跟踪的两个实际但尚未研究的问题。现有方法通常在推理期间跟踪未知时隙值方面是不足的，并且通常难以适应新的域。在本文中，我们提出了一种可转移的对话状态生成器（TRADE），该函数使用复制机制从发声中生成对话状态，从而在预测训练期间未遇到的（三元组，时段，值）三元组时促进知识的传递。我们的模型由发声编码器，插槽门和状态生成器组成，它们在域之间共享。经验
```suggestion
 对域本体的过度依赖和跨域知识共享的缺乏是对话状态跟踪的两个实际但尚未研究的问题。现有方法通常在推理期间跟踪未知时隙值方面是不足的，并且通常难以适应新的域。在本文中，我们提出了一种可转移的对话状态生成器（TRADE），该函数使用复制机制从发声中生成对话状态，从而在预测训练期间未遇到的（三元组，时段，值）三元组时促进知识的传递。我们的模型由发声编码器，插槽门和状态生成器组成，它们在域之间共享。经验结果表明，对于人与人对话数据集MultiWOZ的五个域，TRADE的最新联合目标准确度达到48.62％。此外，我们通过模拟zero-shot和 few-shot对话状态跟踪（针对看不见的域）来显示其传输能力。TRADE在zero-shot域之一中达到了60.58％的联合目标精度，并且能够适应 few-shot的情况而不会忘记已经受过训练的域。 
```

2019-12-15 04:19 UTC, chenquan commented on article/2019/12/2019年对话式AI的10篇重要研究论文.md
> + 香港科技大学和Salesforce Research的研究小组解决了过度依赖领域本体和缺乏跨领域知识共享的问题。在实际情况中，许多时间段在不同的域之间共享所有或部分值（例如，*区域*时间段可以存在于诸如*餐厅*，*酒店*或*出租车的*许多域中），因此跨多个域传输知识对于对话状态跟踪势在必行（DST）模型。研究人员介绍**TRA** nsferable **d** ialogue统计**Ë**生
```suggestion
香港科技大学和Salesforce Research的研究小组解决了过度依赖领域本体和缺乏跨领域知识共享的问题。在实际情况中，许多时间段在不同的域之间共享所有或部分值（例如，*区域*时间段可以存在于诸如*餐厅*，*酒店*或*出租车的*许多域中），因此跨多个域传输知识对于对话状态跟踪势在必行（DST）模型。研究人员介绍**TRA** nsferable **d** ialogue统计**Ë**生成器（TRADE），它利用上下文增强的插槽门和复制机制来跟踪对话历史记录中任何地方提到的插槽值。TRADE跨域共享其参数，并且不需要预定义的本体，从而可以跟踪以前看不到的广告位值。实验证明了该方法的有效性，在具有挑战性的MultiWOZ数据集上，TRADE实现了48.62％的最新联合目标精度。 
```

2019-12-15 04:19 UTC, chenquan commented on article/2019/12/2019年对话式AI的10篇重要研究论文.md
> +- 此外，TRADE在零击域中的一个域中达到了60.58％的联合目标精度，证明了其将知识转移到以前未曾见过的域的能力。
```suggestion
- 此外，TRADE在zero-shot中的一个域中达到了60.58％的联合目标精度，证明了其拥有将知识转移到以前未曾见过的域的能力。
```

2019-12-15 04:19 UTC, chenquan commented on article/2019/12/2019年对话式AI的10篇重要研究论文.md
> +- 实验还证明了该模型能够适应新的少量快照域而不会忘记已经训练好的域的能力。
```suggestion
- 实验还证明了该模型能够适应新的few-shot域而不会忘记已经训练好的域的能力。
```

2019-12-15 04:19 UTC, chenquan commented on article/2019/12/2019年对话式AI的10篇重要研究论文.md
> +- 从其他资源转移知识以进一步提高零击性能。
```suggestion
- 从其他资源转移知识以进一步提高zero-shot性能。
```

2019-12-15 04:19 UTC, chenquan commented on article/2019/12/2019年对话式AI的10篇重要研究论文.md
> +- 收集具有大量域的数据集，以促进对多域对话状态跟踪中的技术的研究。
```suggestion
- 收集了具有大量域的数据集，以促进对多域对话状态跟踪中的技术的研究。
```

2019-12-15 04:19 UTC, chenquan commented on article/2019/12/2019年对话式AI的10篇重要研究论文.md
> +- 当前的研究可以在多域设置中显着提高面向任务的对话系统的性能。
```suggestion
- 当前的研究可以在多域设置中显著提高面向任务的对话系统的性能。
```

2019-12-15 04:19 UTC, chenquan commented on article/2019/12/2019年对话式AI的10篇重要研究论文.md
> +### 2. [**神经对话系统可以有效地使用对话历史吗？实证研究**](https://arxiv.org/abs/1906.01603)**，By CHINNADHURAI SANKAR，SANDEEP SUBRAMANIAN，CHRIS PAL，SARATH CHANDAR和YOSHUA BENGIO**
```suggestion
### 2. [神经对话系统可以有效地使用对话历史吗？实证研究](https://arxiv.org/abs/1906.01603), BY CHINNADHURAI SANKAR, SANDEEP SUBRAMANIAN, CHRIS PAL, SARATH CHANDAR, AND YOSHUA BENGIO
```

2019-12-15 04:19 UTC, chenquan commented on article/2019/12/2019年对话式AI的10篇重要研究论文.md
> +当建立对话代理时，神经生成模型变得越来越流行。它们提供了灵活性，可以轻松地适应新域，并且需要最少的域工程。对这些系统的普遍批评是，它们很少有效地理解或使用可用的对话历史记录。在本文中，我们通过经验方法来研究这些模型在测试时人为地引入非自然变化或扰动其上下文的敏感性，从而了解这些模型如何使用可用的对话历史记录。我们在4个多转对话数据集上对10种不同类型的扰动进行了实验，发现常用的神经对话架构（例如
```suggestion
当建立对话代理时，神经生成模型变得越来越流行。它们提供了灵活性，可以轻松地适应新域，并且需要最少的域工程。对这些系统的普遍批评是，它们很少有效地理解或使用可用的对话历史记录。在本文中，我们通过经验方法来研究这些模型在测试时人为地引入非自然变化或扰动其上下文的敏感性，从而了解这些模型如何使用可用的对话历史记录。我们在4个multi-turn对话数据集上对10种不同类型的扰动进行了实验，发现常用的神经对话体系结构（例如循环神经网络和基于变压器的seq2seq模型）对大多数扰动（例如遗漏或重新排列发音，混排词等）几乎不敏感。通过开源代码，我们相信它将成为将来评估对话框系统的有用诊断工具。
```

2019-12-15 04:19 UTC, chenquan commented on article/2019/12/2019年对话式AI的10篇重要研究论文.md
> +最近引入的生成模型擅长产生流畅的响应，但是这些响应往往很无聊且重复，这通常归因于这些模型对对话历史的理解不足。在本文中，作者试图通过经验研究神经生成模型是否有效地利用了对话历史。为此，他们测试了递归网络和基于变压器的序列到序列模型对各种合成扰动的敏感性。该方法基于以下假设：如果模型对破坏某些类型信息的扰动不敏感，则意味着该模型将最大限度地利用此信息。实验表明，神经生成模型对发声级和词级摄动不敏感
```suggestion
最近引入的生成模型擅长产生流畅的答案，但是这些答案往往很无聊且重复，这通常归因于这些模型对对话历史的理解不足。在本文中，作者试图通过经验研究神经生成模型是否有效地利用了对话历史。为此，他们测试了循环网络和基于transformer的seq-to-seq模型对各种合成扰动的敏感性。该方法基于以下假设：如果模型对破坏某些类型信息的扰动不敏感，则意味着该模型将最大限度地利用此信息。实验表明，神经生成模型对发声级和词级摄动不敏感。
```

2019-12-15 04:19 UTC, chenquan commented on article/2019/12/2019年对话式AI的10篇重要研究论文.md
> +### **3.** [**善于说服：建立个人的有说服力的社会公益**说服对话系统](https://arxiv.org/abs/1906.06725)，BY CHINNADHURAI SANKAR, SANDEEP SUBRAMANIAN, CHRIS PAL, SARATH CHANDAR, AND YOSHUA BENGIO
```suggestion
### 3.[善于说服：建立个人的有说服力的社会公益说服对话系统](https://arxiv.org/abs/1906.06725)，BY CHINNADHURAI SANKAR, SANDEEP SUBRAMANIAN, CHRIS PAL, SARATH CHANDAR, AND YOSHUA BENGIO
```

2019-12-15 04:19 UTC, chenquan commented on article/2019/12/2019年对话式AI的10篇重要研究论文.md
> +开发智能的有说服力的对话代理程序以改变人们的意见和行为以实现社会利益，是推进自动化对话系统的道德发展的前沿。为此，第一步是要了解在人的说服性对话中运用的战略披露和申诉的复杂组织。我们设计了一个在线说服任务，要求一位参与者说服另一位参与者向特定的慈善机构捐款。我们收集了包含1,017个对话的大型数据集，并从一个子集中注释了新兴的说服策略。基于注释，我们构建了带有上下文信息和句子级功能的基线分类器，
```suggestion
开发智能的有说服力的对话智能体程序以改变人们的意见和行为以实现社会利益，是推进自动化对话系统的道德发展的前沿。为此，第一步是要了解在人的说服性对话中运用的战略披露和申诉的复杂组织。我们设计了一个在线说服任务，要求一位参与者说服另一位参与者向特定的慈善机构捐款。我们收集了包含1,017个对话的大型数据集，并从一个子集中注释了新兴的说服策略。基于注释，我们构建了带有上下文信息和句子级功能的基线分类器，以预测语料库中使用的10种说服策略。此外，为了了解个性化的说服流程，我们分析了个人的人口统计学和心理背景之间的关系，包括人格，道德，价值体系及其捐赠意愿。然后，我们根据个人的个人背景分析了哪种类型的说服策略导致了更多的捐赠。这项工作为开发个性化的说服性对话系统奠定了基础。
```

2019-12-15 04:19 UTC, chenquan commented on article/2019/12/2019年对话式AI的10篇重要研究论文.md
> +- AI对话代理的目的通常涉及某种形式的说服，但是对他们有效的说服策略的研究受到限制，因为说服的研究传统上是社会科学而不是AI工程的一部分。
```suggestion
- AI对话智能体的目的通常涉及某种形式的说服，但是对他们有效的说服策略的研究受到限制，因为说服的研究传统上是社会科学而不是AI工程的一部分。
```

2019-12-15 04:19 UTC, chenquan commented on article/2019/12/2019年对话式AI的10篇重要研究论文.md
> +  - 上下文嵌入；
```suggestion
  - 上下文嵌入
```

2019-12-15 04:19 UTC, chenquan commented on article/2019/12/2019年对话式AI的10篇重要研究论文.md
> +  - 句子级功能。
```suggestion
  - 句子级功能
```

2019-12-15 04:19 UTC, chenquan commented on article/2019/12/2019年对话式AI的10篇重要研究论文.md
> +### **4.** [**OPENDIALKG：基于注意力的知识图遍历的可解释性**](https://www.semanticscholar.org/paper/OpenDialKG%3A-Explainable-Conversational-Reasoning-Moon-Shah/0d3c68c207fc83fb402b7217811af22066300fc9)[**对话推理**](htt
```suggestion
### 4. [OPENDIALKG：基于注意力的知识图遍历的可解释性对话推理](https://www.semanticscholar.org/paper/OpenDialKG%3A-Explainable-Conversational-Reasoning-Moon-Shah/0d3c68c207fc83fb402b7217811af22066300fc9)，By SEUNGWHAN MOON，PARARTH SHAH，ANUJ KUMAR和RAJEN SUBBA
```

2019-12-15 04:19 UTC, chenquan commented on article/2019/12/2019年对话式AI的10篇重要研究论文.md
> +我们研究了一种对话推理模型，该模型策略性地遍历了大型公共事实知识图（KG），以引入引人入胜且在上下文中不同的实体和属性。在这项研究中，我们收集了一个新的**开放**式**Dial** og **KG**平行语料库，称为**OpenDialKG**，其中来自人与人角色扮演对话的15K的每个讲话都用地面真实引用手动注释，这些引用来自具有1M +事实的大型KG的相应实体和路径。然后，我们提出DialK
```suggestion
我们研究了一种对话推理模型，该模型策略性地遍历了大型公共事实知识图（KG），以引入让人感兴趣且在上下文中不同的实体和属性。在这项研究中，我们收集了一个新的**Open-ended Dialog**↔ **KG**平行语料库，称为**OpenDialKG**，其中来自人与人角色扮演对话的15K的每个讲话都用地面真实引用手动注释，这些引用来自具有1M +事实的大型KG的相应实体和路径。然后，我们提出DialKG Walker模型，该模型学习对话上下文作为KG上的结构化遍历的对话上下文的符号转换，并预测自然实体，通过新颖的领域无关，基于注意力的图路径解码器引入给定的先前对话上下文。自动和人工评估表明，在域内和跨域任务中，我们的模型都可以比最新的基准或基于规则的模型检索更多自然和类似人类的响应。所提出的模型还为检索到的每个实体生成了KG行走路径，从而提供了一种解释对话推理的自然方法。
```

2019-12-15 04:19 UTC, chenquan commented on article/2019/12/2019年对话式AI的10篇重要研究论文.md
> +  - 一个并行的**零击学习模型**，该**模型**利用先前的句子，对话和KG上下文根据候选实体的相关性和路径得分对其进行排名。
```suggestion
  - 一个并行的**zero-shot 学习模型**，该**模型**利用先前的句子，对话和KG上下文根据候选实体的相关性和路径得分对其进行排名。
```

2019-12-15 04:19 UTC, chenquan commented on article/2019/12/2019年对话式AI的10篇重要研究论文.md
> +- 通过提及相关实体和属性，使跨域和任务（例如，聊天，建议）的聊天机器人能够生成更自然和更具吸引力的响应。
```suggestion
- 通过提及相关实体和属性，使跨域和任务（例如，聊天，建议）的聊天机器人能够生成更自然和更具吸引力的回答。
```

2019-12-15 04:19 UTC, chenquan commented on article/2019/12/2019年对话式AI的10篇重要研究论文.md
> +### **5.** [**对话互动的动态说话人模型**](https://www.aclweb.org/anthology/N19-1284)，BY HAO CHENG, HAO FANG, MARI OSTENDORF
```suggestion
### 5. [对话互动的动态说话人模型](https://www.aclweb.org/anthology/N19-1284)，BY HAO CHENG, HAO FANG, MARI OSTENDORF
```

2019-12-15 04:19 UTC, chenquan commented on article/2019/12/2019年对话式AI的10篇重要研究论文.md
> +说话者的个体差异反映在他们的语言使用以及他们的兴趣和观点上。表征这些差异对于人机交互以及人与人之间的对话分析很有用。在这项工作中，我们介绍了一种神经模型，用于学习在对话上下文中嵌入动态更新的说话者。初始模型训练是无监督的，使用上下文相关的语言生成作为目标，而上下文是对话历史记录。进一步的微调可以利用与任务有关的监督培训。研究表明，学习者对说话人的神经表示对于社交机器人中的内容排名和人与人对话中的
```suggestion
说话者的个体差异反映在他们的语言使用以及他们的兴趣和观点上。表示这些差异对于人机交互以及人与人之间的对话分析很有用。在这项工作中，我们介绍了一种神经模型，用于学习在对话上下文中嵌入动态更新的说话者。初始模型训练是无监督的，使用上下文相关的语言生成作为目标，而上下文是对话历史记录。进一步的微调可以利用与任务有关的监督培训。研究表明，学习者对说话人的神经表示对于社交机器人中的内容排名和人与人对话中的对话行为预测非常有用。
```

2019-12-15 04:19 UTC, chenquan commented on article/2019/12/2019年对话式AI的10篇重要研究论文.md
> +华盛顿大学的研究小组建议，了解用户之间的个体差异对预测下一个对话行为很有用。为了发现这些个体差异，研究人员建议使用无监督的神经模型，该模型从对话历史中学习说话者嵌入。此外，为了捕获随时间的变化并在有新数据可用时改进说话者表示，引入的模型的结构允许在每次对话时动态更新说话者嵌入向量。实验结果表明，具有动态说话者嵌入功能的模型在预测人与人之间的机器人对话中的用户主题决策以及对人与人对话中的对话行为进
```suggestion
华盛顿大学的研究小组建议，了解用户之间的个体差异对预测下一个对话行为很有用。为了发现这些个体差异，研究人员建议使用无监督的神经模型，该模型从对话历史中学习说话者嵌入。此外，为了捕获随时间的变化并在有新数据可用时改进说话者表征，引入的模型的结构允许在每次对话时动态更新说话者嵌入向量。实验结果表明，具有动态说话者嵌入功能的模型在预测人与人之间的机器人对话中的用户主题决策以及对人与人对话中的对话行为进行分类时，优于基线。
```

2019-12-15 04:19 UTC, chenquan commented on article/2019/12/2019年对话式AI的10篇重要研究论文.md
> +  - 该模型以无监督的方式进行训练，以仅通过依靠该说话者的对话历史来学习每个说话者的表示。
```suggestion
  - 该模型以无监督的方式进行训练，以仅通过依靠该说话者的对话历史来学习每个说话者的表征。
```

2019-12-15 04:19 UTC, chenquan commented on article/2019/12/2019年对话式AI的10篇重要研究论文.md
> +  由三个部分组成：
![image](https://user-images.githubusercontent.com/20548053/70858035-c3aee180-1f34-11ea-94c5-e00ef8522d56.png)
这部分改成
```
该**动态说话者模型**由三个部分组成
```

2019-12-15 07:16 UTC, chenquan requested changes

2019-12-15 07:16 UTC, chenquan commented on article/2019/12/2019年对话式AI的10篇重要研究论文.md
> +### **4.**  \4. [OPENDIALKG：基于注意力的知识图遍历的可解释性对话推理](https://www.semanticscholar.org/paper/OpenDialKG%3A-Explainable-Conversational-Reasoning-Moon-Shah/0d3c68c207fc83fb402b7217811af22066300fc9)，By SEUNG
```suggestion
### 4.[OPENDIALKG：基于注意力的知识图遍历的可解释性对话推理](https://www.semanticscholar.org/paper/OpenDialKG%3A-Explainable-Conversational-Reasoning-Moon-Shah/0d3c68c207fc83fb402b7217811af22066300fc9)，By SEUNGWHAN MOON，PARARTH SHAH，ANUJ KUMAR和RAJEN SUBBA 
```

2019-12-15 07:16 UTC, chenquan commented on article/2019/12/2019年对话式AI的10篇重要研究论文.md
> +  的新模型，其中包括：
![image](https://user-images.githubusercontent.com/20548053/70859361-1f856480-1f4d-11ea-9659-15a60906c832.png)
```
特别是，研究小组提出了一种名为**DialKG Walker**的新模型，其中包括：
```

2019-12-15 07:16 UTC, chenquan commented on article/2019/12/2019年对话式AI的10篇重要研究论文.md
> +麻省理工学院的研究小组调查了评估开放域对话系统的问题。人是评估对话系统质量的最终权威，但是获得人的评级通常是相当昂贵且困难的过程。为了克服这些挑战并仍然获得可靠的评估，麻省理工学院的团队引入了一种新颖的框架来评估对话质量得分，该得分与人类评级具有很高的统计意义上的相关性。具体来说，他们提出了一系列基于心理学的指标，然后在给定这些指标的情况下拟合了一种功能，以预测人类对对话质量的评估。机器人的质量
```suggestion
麻省理工学院的研究小组调查了评估开放域对话系统的问题。人是评估对话系统质量的最终权威，但是获得人的评级通常是相当昂贵且困难的过程。为了克服这些挑战并仍然获得可靠的评估，麻省理工学院的团队引入了一种新颖的框架来评估对话质量得分，该得分与人类评级具有很高的统计意义上的相关性。具体来说，他们提出了一系列基于心理学的指标，然后在给定这些指标的情况下拟合了一种功能，以预测人类对对话质量的评估。机器人的质量通过固定轮次中的自打进行评估，其中机器人会生成发声，并在下一轮中将其反馈为输入。实验证实，引入的self-play框架以及基于心理学的自动度量标准可以为会话评估提供良好的智能体。
```

2019-12-15 07:21 UTC, chenquan commented
- https://github.com/opensourceai/spark-plan/pull/57#discussion_r357958551
- https://github.com/opensourceai/spark-plan/pull/57#discussion_r357958404
处理一下

2019-12-20 02:08 UTC, merged